/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_test_utils_JniUtil */

#ifndef _Included_com_example_administrator_test_utils_JniUtil
#define _Included_com_example_administrator_test_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_test_utils_JniUtil
 * Method:    getSomeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_test_utils_JniUtil_getSomeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
