/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_administrator_test_utils_JniUtil.h>

JNIEXPORT jstring JNICALL Java_com_example_administrator_test_utils_JniUtil_getSomeString(JNIEnv * env, jobject obj)
{
    return env -> NewStringUTF("123214124");
}

